syntax = "proto3";

//the class name
package hvcomm;

// The generic request message
message RequestMessage {
    string client_name = 1;
    string function_name = 2;
    repeated string parameters = 3;
}

// The generic response message
message ResponseMessage {
    string message = 1;
    int32 status = 2;
}

// The gRPC service definition
service ExampleService {
    rpc SayHello (RequestMessage) returns (ResponseMessage);
}

// [service] Request GPU instance
service CUDAAPIService {
    rpc CallCudaFunction(RequestMessage) returns (ResponseMessage);
}