syntax = "proto3";

package hvcomm;

// The generic request message
message RequestMessage {
    string client_name = 1;
    string function_name = 2;
    repeated string string_parameters = 3;
    repeated uint64 scalar_parameters = 4;
}

// The generic response message
message ResponseMessage {
    int32 curesult = 1;
    uint64 scalar = 2;
}

// The gRPC service definition
service ExampleService {
    rpc SayHello (RequestMessage) returns (ResponseMessage);
}

// [service] Request GPU instance
service CUDAAPIService {
    rpc CallCudaFunction(RequestMessage) returns (ResponseMessage);
}