// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hvcomm.proto
// Protobuf C++ Version: 5.29.1

#include "hvcomm.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace hvcomm {

inline constexpr ResponseMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseMessage::ResponseMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseMessageDefaultTypeInternal() {}
  union {
    ResponseMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseMessageDefaultTypeInternal _ResponseMessage_default_instance_;

inline constexpr RequestMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : parameters_{},
        client_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        function_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestMessage::RequestMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestMessageDefaultTypeInternal() {}
  union {
    RequestMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestMessageDefaultTypeInternal _RequestMessage_default_instance_;
}  // namespace hvcomm
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_hvcomm_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_hvcomm_2eproto = nullptr;
const ::uint32_t
    TableStruct_hvcomm_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::hvcomm::RequestMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::hvcomm::RequestMessage, _impl_.client_name_),
        PROTOBUF_FIELD_OFFSET(::hvcomm::RequestMessage, _impl_.function_name_),
        PROTOBUF_FIELD_OFFSET(::hvcomm::RequestMessage, _impl_.parameters_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::hvcomm::ResponseMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::hvcomm::ResponseMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::hvcomm::ResponseMessage, _impl_.status_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::hvcomm::RequestMessage)},
        {11, -1, -1, sizeof(::hvcomm::ResponseMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::hvcomm::_RequestMessage_default_instance_._instance,
    &::hvcomm::_ResponseMessage_default_instance_._instance,
};
const char descriptor_table_protodef_hvcomm_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014hvcomm.proto\022\006hvcomm\"P\n\016RequestMessage"
    "\022\023\n\013client_name\030\001 \001(\t\022\025\n\rfunction_name\030\002"
    " \001(\t\022\022\n\nparameters\030\003 \003(\t\"2\n\017ResponseMess"
    "age\022\017\n\007message\030\001 \001(\t\022\016\n\006status\030\002 \001(\0052M\n\016"
    "ExampleService\022;\n\010SayHello\022\026.hvcomm.Requ"
    "estMessage\032\027.hvcomm.ResponseMessage2U\n\016C"
    "UDAAPIService\022C\n\020CallCudaFunction\022\026.hvco"
    "mm.RequestMessage\032\027.hvcomm.ResponseMessa"
    "geb\006proto3"
};
static ::absl::once_flag descriptor_table_hvcomm_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_hvcomm_2eproto = {
    false,
    false,
    330,
    descriptor_table_protodef_hvcomm_2eproto,
    "hvcomm.proto",
    &descriptor_table_hvcomm_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_hvcomm_2eproto::offsets,
    file_level_enum_descriptors_hvcomm_2eproto,
    file_level_service_descriptors_hvcomm_2eproto,
};
namespace hvcomm {
// ===================================================================

class RequestMessage::_Internal {
 public:
};

RequestMessage::RequestMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hvcomm.RequestMessage)
}
inline PROTOBUF_NDEBUG_INLINE RequestMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::hvcomm::RequestMessage& from_msg)
      : parameters_{visibility, arena, from.parameters_},
        client_name_(arena, from.client_name_),
        function_name_(arena, from.function_name_),
        _cached_size_{0} {}

RequestMessage::RequestMessage(
    ::google::protobuf::Arena* arena,
    const RequestMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:hvcomm.RequestMessage)
}
inline PROTOBUF_NDEBUG_INLINE RequestMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : parameters_{visibility, arena},
        client_name_(arena),
        function_name_(arena),
        _cached_size_{0} {}

inline void RequestMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestMessage::~RequestMessage() {
  // @@protoc_insertion_point(destructor:hvcomm.RequestMessage)
  SharedDtor(*this);
}
inline void RequestMessage::SharedDtor(MessageLite& self) {
  RequestMessage& this_ = static_cast<RequestMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.client_name_.Destroy();
  this_._impl_.function_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RequestMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RequestMessage(arena);
}
constexpr auto RequestMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.parameters_) +
          decltype(RequestMessage::_impl_.parameters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(RequestMessage), alignof(RequestMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RequestMessage::PlacementNew_,
                                 sizeof(RequestMessage),
                                 alignof(RequestMessage));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RequestMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RequestMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RequestMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RequestMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RequestMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RequestMessage>(), &RequestMessage::ByteSizeLong,
            &RequestMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_._cached_size_),
        false,
    },
    &RequestMessage::kDescriptorMethods,
    &descriptor_table_hvcomm_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RequestMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 64, 2> RequestMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hvcomm::RequestMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string client_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.client_name_)}},
    // string function_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.function_name_)}},
    // repeated string parameters = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.parameters_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_name = 1;
    {PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.client_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string function_name = 2;
    {PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.function_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string parameters = 3;
    {PROTOBUF_FIELD_OFFSET(RequestMessage, _impl_.parameters_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\25\13\15\12\0\0\0\0"
    "hvcomm.RequestMessage"
    "client_name"
    "function_name"
    "parameters"
  }},
};

PROTOBUF_NOINLINE void RequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:hvcomm.RequestMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.parameters_.Clear();
  _impl_.client_name_.ClearToEmpty();
  _impl_.function_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RequestMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RequestMessage& this_ = static_cast<const RequestMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RequestMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RequestMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:hvcomm.RequestMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string client_name = 1;
          if (!this_._internal_client_name().empty()) {
            const std::string& _s = this_._internal_client_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hvcomm.RequestMessage.client_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string function_name = 2;
          if (!this_._internal_function_name().empty()) {
            const std::string& _s = this_._internal_function_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hvcomm.RequestMessage.function_name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated string parameters = 3;
          for (int i = 0, n = this_._internal_parameters_size(); i < n; ++i) {
            const auto& s = this_._internal_parameters().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hvcomm.RequestMessage.parameters");
            target = stream->WriteString(3, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:hvcomm.RequestMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RequestMessage::ByteSizeLong(const MessageLite& base) {
          const RequestMessage& this_ = static_cast<const RequestMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RequestMessage::ByteSizeLong() const {
          const RequestMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:hvcomm.RequestMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string parameters = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_parameters().size());
              for (int i = 0, n = this_._internal_parameters().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_parameters().Get(i));
              }
            }
          }
           {
            // string client_name = 1;
            if (!this_._internal_client_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_client_name());
            }
            // string function_name = 2;
            if (!this_._internal_function_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_function_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RequestMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestMessage*>(&to_msg);
  auto& from = static_cast<const RequestMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hvcomm.RequestMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_parameters()->MergeFrom(from._internal_parameters());
  if (!from._internal_client_name().empty()) {
    _this->_internal_set_client_name(from._internal_client_name());
  }
  if (!from._internal_function_name().empty()) {
    _this->_internal_set_function_name(from._internal_function_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestMessage::CopyFrom(const RequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hvcomm.RequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestMessage::InternalSwap(RequestMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.parameters_.InternalSwap(&other->_impl_.parameters_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_name_, &other->_impl_.client_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.function_name_, &other->_impl_.function_name_, arena);
}

::google::protobuf::Metadata RequestMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResponseMessage::_Internal {
 public:
};

ResponseMessage::ResponseMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hvcomm.ResponseMessage)
}
inline PROTOBUF_NDEBUG_INLINE ResponseMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::hvcomm::ResponseMessage& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ResponseMessage::ResponseMessage(
    ::google::protobuf::Arena* arena,
    const ResponseMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResponseMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:hvcomm.ResponseMessage)
}
inline PROTOBUF_NDEBUG_INLINE ResponseMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ResponseMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ResponseMessage::~ResponseMessage() {
  // @@protoc_insertion_point(destructor:hvcomm.ResponseMessage)
  SharedDtor(*this);
}
inline void ResponseMessage::SharedDtor(MessageLite& self) {
  ResponseMessage& this_ = static_cast<ResponseMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResponseMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResponseMessage(arena);
}
constexpr auto ResponseMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResponseMessage),
                                            alignof(ResponseMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResponseMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResponseMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResponseMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResponseMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResponseMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResponseMessage>(), &ResponseMessage::ByteSizeLong,
            &ResponseMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_._cached_size_),
        false,
    },
    &ResponseMessage::kDescriptorMethods,
    &descriptor_table_hvcomm_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResponseMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> ResponseMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hvcomm::ResponseMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 status = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponseMessage, _impl_.status_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.status_)}},
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 status = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\26\7\0\0\0\0\0\0"
    "hvcomm.ResponseMessage"
    "message"
  }},
};

PROTOBUF_NOINLINE void ResponseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:hvcomm.ResponseMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResponseMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResponseMessage& this_ = static_cast<const ResponseMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResponseMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResponseMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:hvcomm.ResponseMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hvcomm.ResponseMessage.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 status = 2;
          if (this_._internal_status() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_status(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:hvcomm.ResponseMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResponseMessage::ByteSizeLong(const MessageLite& base) {
          const ResponseMessage& this_ = static_cast<const ResponseMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResponseMessage::ByteSizeLong() const {
          const ResponseMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:hvcomm.ResponseMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 status = 2;
            if (this_._internal_status() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResponseMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResponseMessage*>(&to_msg);
  auto& from = static_cast<const ResponseMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hvcomm.ResponseMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseMessage::CopyFrom(const ResponseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hvcomm.ResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseMessage::InternalSwap(ResponseMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata ResponseMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace hvcomm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_hvcomm_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
