// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hvcomm.proto
#ifndef GRPC_hvcomm_2eproto__INCLUDED
#define GRPC_hvcomm_2eproto__INCLUDED

#include "hvcomm.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace hvcomm {

// The gRPC service definition
class ExampleService final {
 public:
  static constexpr char const* service_full_name() {
    return "hvcomm.ExampleService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>> AsyncSayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>> AsyncSayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::hvcomm::RequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::hvcomm::ResponseMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hvcomm::RequestMessage,::hvcomm::ResponseMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<Service > StreamedService;
};

// [service] Request GPU instance
class CUDAAPIService final {
 public:
  static constexpr char const* service_full_name() {
    return "hvcomm.CUDAAPIService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>> AsyncCallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>>(AsyncCallCudaFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>> PrepareAsyncCallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>>(PrepareAsyncCallCudaFunctionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>* AsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hvcomm::ResponseMessage>* PrepareAsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>> AsyncCallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>>(AsyncCallCudaFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>> PrepareAsyncCallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>>(PrepareAsyncCallCudaFunctionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)>) override;
      void CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* AsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* PrepareAsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CallCudaFunction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CallCudaFunction(::grpc::ServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallCudaFunction(::grpc::ServerContext* context, ::hvcomm::RequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::hvcomm::ResponseMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CallCudaFunction<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response) { return this->CallCudaFunction(context, request, response); }));}
    void SetMessageAllocatorFor_CallCudaFunction(
        ::grpc::MessageAllocator< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallCudaFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CallCudaFunction<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallCudaFunction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CallCudaFunction(context, request, response); }));
    }
    ~WithRawCallbackMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallCudaFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CallCudaFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CallCudaFunction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage>* streamer) {
                       return this->StreamedCallCudaFunction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CallCudaFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallCudaFunction(::grpc::ServerContext* /*context*/, const ::hvcomm::RequestMessage* /*request*/, ::hvcomm::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCallCudaFunction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hvcomm::RequestMessage,::hvcomm::ResponseMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CallCudaFunction<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CallCudaFunction<Service > StreamedService;
};

}  // namespace hvcomm


#endif  // GRPC_hvcomm_2eproto__INCLUDED
