// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hvcomm.proto
// Protobuf C++ Version: 5.29.1

#ifndef hvcomm_2eproto_2epb_2eh
#define hvcomm_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_hvcomm_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_hvcomm_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_hvcomm_2eproto;
namespace hvcomm {
class RequestMessage;
struct RequestMessageDefaultTypeInternal;
extern RequestMessageDefaultTypeInternal _RequestMessage_default_instance_;
class ResponseMessage;
struct ResponseMessageDefaultTypeInternal;
extern ResponseMessageDefaultTypeInternal _ResponseMessage_default_instance_;
}  // namespace hvcomm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace hvcomm {

// ===================================================================


// -------------------------------------------------------------------

class ResponseMessage final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:hvcomm.ResponseMessage) */ {
 public:
  inline ResponseMessage() : ResponseMessage(nullptr) {}
  ~ResponseMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResponseMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResponseMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResponseMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResponseMessage(const ResponseMessage& from) : ResponseMessage(nullptr, from) {}
  inline ResponseMessage(ResponseMessage&& from) noexcept
      : ResponseMessage(nullptr, std::move(from)) {}
  inline ResponseMessage& operator=(const ResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseMessage& operator=(ResponseMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResponseMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResponseMessage* internal_default_instance() {
    return reinterpret_cast<const ResponseMessage*>(
        &_ResponseMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ResponseMessage& a, ResponseMessage& b) { a.Swap(&b); }
  inline void Swap(ResponseMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResponseMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResponseMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResponseMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResponseMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResponseMessage& from) { ResponseMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResponseMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "hvcomm.ResponseMessage"; }

 protected:
  explicit ResponseMessage(::google::protobuf::Arena* arena);
  ResponseMessage(::google::protobuf::Arena* arena, const ResponseMessage& from);
  ResponseMessage(::google::protobuf::Arena* arena, ResponseMessage&& from) noexcept
      : ResponseMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScalarFieldNumber = 2,
    kCuresultFieldNumber = 1,
  };
  // uint64 scalar = 2;
  void clear_scalar() ;
  ::uint64_t scalar() const;
  void set_scalar(::uint64_t value);

  private:
  ::uint64_t _internal_scalar() const;
  void _internal_set_scalar(::uint64_t value);

  public:
  // int32 curesult = 1;
  void clear_curesult() ;
  ::int32_t curesult() const;
  void set_curesult(::int32_t value);

  private:
  ::int32_t _internal_curesult() const;
  void _internal_set_curesult(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:hvcomm.ResponseMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResponseMessage& from_msg);
    ::uint64_t scalar_;
    ::int32_t curesult_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hvcomm_2eproto;
};
// -------------------------------------------------------------------

class RequestMessage final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:hvcomm.RequestMessage) */ {
 public:
  inline RequestMessage() : RequestMessage(nullptr) {}
  ~RequestMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline RequestMessage(const RequestMessage& from) : RequestMessage(nullptr, from) {}
  inline RequestMessage(RequestMessage&& from) noexcept
      : RequestMessage(nullptr, std::move(from)) {}
  inline RequestMessage& operator=(const RequestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestMessage& operator=(RequestMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestMessage* internal_default_instance() {
    return reinterpret_cast<const RequestMessage*>(
        &_RequestMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RequestMessage& a, RequestMessage& b) { a.Swap(&b); }
  inline void Swap(RequestMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestMessage& from) { RequestMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "hvcomm.RequestMessage"; }

 protected:
  explicit RequestMessage(::google::protobuf::Arena* arena);
  RequestMessage(::google::protobuf::Arena* arena, const RequestMessage& from);
  RequestMessage(::google::protobuf::Arena* arena, RequestMessage&& from) noexcept
      : RequestMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStringParametersFieldNumber = 3,
    kScalarParametersFieldNumber = 4,
    kClientNameFieldNumber = 1,
    kFunctionNameFieldNumber = 2,
  };
  // repeated string string_parameters = 3;
  int string_parameters_size() const;
  private:
  int _internal_string_parameters_size() const;

  public:
  void clear_string_parameters() ;
  const std::string& string_parameters(int index) const;
  std::string* mutable_string_parameters(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_string_parameters(int index, Arg_&& value, Args_... args);
  std::string* add_string_parameters();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_string_parameters(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& string_parameters() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_string_parameters();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_string_parameters() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_string_parameters();

  public:
  // repeated uint64 scalar_parameters = 4;
  int scalar_parameters_size() const;
  private:
  int _internal_scalar_parameters_size() const;

  public:
  void clear_scalar_parameters() ;
  ::uint64_t scalar_parameters(int index) const;
  void set_scalar_parameters(int index, ::uint64_t value);
  void add_scalar_parameters(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& scalar_parameters() const;
  ::google::protobuf::RepeatedField<::uint64_t>* mutable_scalar_parameters();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_scalar_parameters() const;
  ::google::protobuf::RepeatedField<::uint64_t>* _internal_mutable_scalar_parameters();

  public:
  // string client_name = 1;
  void clear_client_name() ;
  const std::string& client_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_client_name(Arg_&& arg, Args_... args);
  std::string* mutable_client_name();
  PROTOBUF_NODISCARD std::string* release_client_name();
  void set_allocated_client_name(std::string* value);

  private:
  const std::string& _internal_client_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_name(
      const std::string& value);
  std::string* _internal_mutable_client_name();

  public:
  // string function_name = 2;
  void clear_function_name() ;
  const std::string& function_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_function_name(Arg_&& arg, Args_... args);
  std::string* mutable_function_name();
  PROTOBUF_NODISCARD std::string* release_function_name();
  void set_allocated_function_name(std::string* value);

  private:
  const std::string& _internal_function_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_function_name(
      const std::string& value);
  std::string* _internal_mutable_function_name();

  public:
  // @@protoc_insertion_point(class_scope:hvcomm.RequestMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      71, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RequestMessage& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> string_parameters_;
    ::google::protobuf::RepeatedField<::uint64_t> scalar_parameters_;
    ::google::protobuf::internal::CachedSize _scalar_parameters_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr client_name_;
    ::google::protobuf::internal::ArenaStringPtr function_name_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hvcomm_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RequestMessage

// string client_name = 1;
inline void RequestMessage::clear_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.ClearToEmpty();
}
inline const std::string& RequestMessage::client_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hvcomm.RequestMessage.client_name)
  return _internal_client_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RequestMessage::set_client_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hvcomm.RequestMessage.client_name)
}
inline std::string* RequestMessage::mutable_client_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_client_name();
  // @@protoc_insertion_point(field_mutable:hvcomm.RequestMessage.client_name)
  return _s;
}
inline const std::string& RequestMessage::_internal_client_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_name_.Get();
}
inline void RequestMessage::_internal_set_client_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.Set(value, GetArena());
}
inline std::string* RequestMessage::_internal_mutable_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.client_name_.Mutable( GetArena());
}
inline std::string* RequestMessage::release_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hvcomm.RequestMessage.client_name)
  return _impl_.client_name_.Release();
}
inline void RequestMessage::set_allocated_client_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.client_name_.IsDefault()) {
    _impl_.client_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hvcomm.RequestMessage.client_name)
}

// string function_name = 2;
inline void RequestMessage::clear_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.ClearToEmpty();
}
inline const std::string& RequestMessage::function_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hvcomm.RequestMessage.function_name)
  return _internal_function_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RequestMessage::set_function_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hvcomm.RequestMessage.function_name)
}
inline std::string* RequestMessage::mutable_function_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_function_name();
  // @@protoc_insertion_point(field_mutable:hvcomm.RequestMessage.function_name)
  return _s;
}
inline const std::string& RequestMessage::_internal_function_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.function_name_.Get();
}
inline void RequestMessage::_internal_set_function_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.Set(value, GetArena());
}
inline std::string* RequestMessage::_internal_mutable_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.function_name_.Mutable( GetArena());
}
inline std::string* RequestMessage::release_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hvcomm.RequestMessage.function_name)
  return _impl_.function_name_.Release();
}
inline void RequestMessage::set_allocated_function_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.function_name_.IsDefault()) {
    _impl_.function_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hvcomm.RequestMessage.function_name)
}

// repeated string string_parameters = 3;
inline int RequestMessage::_internal_string_parameters_size() const {
  return _internal_string_parameters().size();
}
inline int RequestMessage::string_parameters_size() const {
  return _internal_string_parameters_size();
}
inline void RequestMessage::clear_string_parameters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_parameters_.Clear();
}
inline std::string* RequestMessage::add_string_parameters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_string_parameters()->Add();
  // @@protoc_insertion_point(field_add_mutable:hvcomm.RequestMessage.string_parameters)
  return _s;
}
inline const std::string& RequestMessage::string_parameters(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hvcomm.RequestMessage.string_parameters)
  return _internal_string_parameters().Get(index);
}
inline std::string* RequestMessage::mutable_string_parameters(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:hvcomm.RequestMessage.string_parameters)
  return _internal_mutable_string_parameters()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void RequestMessage::set_string_parameters(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_string_parameters()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:hvcomm.RequestMessage.string_parameters)
}
template <typename Arg_, typename... Args_>
inline void RequestMessage::add_string_parameters(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_string_parameters(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:hvcomm.RequestMessage.string_parameters)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
RequestMessage::string_parameters() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:hvcomm.RequestMessage.string_parameters)
  return _internal_string_parameters();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
RequestMessage::mutable_string_parameters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:hvcomm.RequestMessage.string_parameters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_string_parameters();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
RequestMessage::_internal_string_parameters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.string_parameters_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
RequestMessage::_internal_mutable_string_parameters() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.string_parameters_;
}

// repeated uint64 scalar_parameters = 4;
inline int RequestMessage::_internal_scalar_parameters_size() const {
  return _internal_scalar_parameters().size();
}
inline int RequestMessage::scalar_parameters_size() const {
  return _internal_scalar_parameters_size();
}
inline void RequestMessage::clear_scalar_parameters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scalar_parameters_.Clear();
}
inline ::uint64_t RequestMessage::scalar_parameters(int index) const {
  // @@protoc_insertion_point(field_get:hvcomm.RequestMessage.scalar_parameters)
  return _internal_scalar_parameters().Get(index);
}
inline void RequestMessage::set_scalar_parameters(int index, ::uint64_t value) {
  _internal_mutable_scalar_parameters()->Set(index, value);
  // @@protoc_insertion_point(field_set:hvcomm.RequestMessage.scalar_parameters)
}
inline void RequestMessage::add_scalar_parameters(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_scalar_parameters()->Add(value);
  // @@protoc_insertion_point(field_add:hvcomm.RequestMessage.scalar_parameters)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& RequestMessage::scalar_parameters() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:hvcomm.RequestMessage.scalar_parameters)
  return _internal_scalar_parameters();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* RequestMessage::mutable_scalar_parameters()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:hvcomm.RequestMessage.scalar_parameters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_scalar_parameters();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
RequestMessage::_internal_scalar_parameters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scalar_parameters_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* RequestMessage::_internal_mutable_scalar_parameters() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.scalar_parameters_;
}

// -------------------------------------------------------------------

// ResponseMessage

// int32 curesult = 1;
inline void ResponseMessage::clear_curesult() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curesult_ = 0;
}
inline ::int32_t ResponseMessage::curesult() const {
  // @@protoc_insertion_point(field_get:hvcomm.ResponseMessage.curesult)
  return _internal_curesult();
}
inline void ResponseMessage::set_curesult(::int32_t value) {
  _internal_set_curesult(value);
  // @@protoc_insertion_point(field_set:hvcomm.ResponseMessage.curesult)
}
inline ::int32_t ResponseMessage::_internal_curesult() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.curesult_;
}
inline void ResponseMessage::_internal_set_curesult(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curesult_ = value;
}

// uint64 scalar = 2;
inline void ResponseMessage::clear_scalar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scalar_ = ::uint64_t{0u};
}
inline ::uint64_t ResponseMessage::scalar() const {
  // @@protoc_insertion_point(field_get:hvcomm.ResponseMessage.scalar)
  return _internal_scalar();
}
inline void ResponseMessage::set_scalar(::uint64_t value) {
  _internal_set_scalar(value);
  // @@protoc_insertion_point(field_set:hvcomm.ResponseMessage.scalar)
}
inline ::uint64_t ResponseMessage::_internal_scalar() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scalar_;
}
inline void ResponseMessage::_internal_set_scalar(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scalar_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace hvcomm


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // hvcomm_2eproto_2epb_2eh
