// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hvcomm.proto

#include "hvcomm.pb.h"
#include "hvcomm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hvcomm {

static const char* ExampleService_method_names[] = {
  "/hvcomm.ExampleService/SayHello",
};

std::unique_ptr< ExampleService::Stub> ExampleService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ExampleService::Stub> stub(new ExampleService::Stub(channel, options));
  return stub;
}

ExampleService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(ExampleService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ExampleService::Stub::SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void ExampleService::Stub::async::SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void ExampleService::Stub::async::SayHello(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* ExampleService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hvcomm::ResponseMessage, ::hvcomm::RequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* ExampleService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

ExampleService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExampleService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExampleService::Service, ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExampleService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hvcomm::RequestMessage* req,
             ::hvcomm::ResponseMessage* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
}

ExampleService::Service::~Service() {
}

::grpc::Status ExampleService::Service::SayHello(::grpc::ServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* CUDAAPIService_method_names[] = {
  "/hvcomm.CUDAAPIService/CallCudaFunction",
};

std::unique_ptr< CUDAAPIService::Stub> CUDAAPIService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CUDAAPIService::Stub> stub(new CUDAAPIService::Stub(channel, options));
  return stub;
}

CUDAAPIService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CallCudaFunction_(CUDAAPIService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CUDAAPIService::Stub::CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::hvcomm::ResponseMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallCudaFunction_, context, request, response);
}

void CUDAAPIService::Stub::async::CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallCudaFunction_, context, request, response, std::move(f));
}

void CUDAAPIService::Stub::async::CallCudaFunction(::grpc::ClientContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallCudaFunction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* CUDAAPIService::Stub::PrepareAsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hvcomm::ResponseMessage, ::hvcomm::RequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallCudaFunction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hvcomm::ResponseMessage>* CUDAAPIService::Stub::AsyncCallCudaFunctionRaw(::grpc::ClientContext* context, const ::hvcomm::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallCudaFunctionRaw(context, request, cq);
  result->StartCall();
  return result;
}

CUDAAPIService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CUDAAPIService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CUDAAPIService::Service, ::hvcomm::RequestMessage, ::hvcomm::ResponseMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CUDAAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hvcomm::RequestMessage* req,
             ::hvcomm::ResponseMessage* resp) {
               return service->CallCudaFunction(ctx, req, resp);
             }, this)));
}

CUDAAPIService::Service::~Service() {
}

::grpc::Status CUDAAPIService::Service::CallCudaFunction(::grpc::ServerContext* context, const ::hvcomm::RequestMessage* request, ::hvcomm::ResponseMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hvcomm

